#!/bin/bash

VERSION=v1.1.5

set -e

help() {
  echo "Usage:"
  echo "  zmicro package install speedtest <args...>"
  echo ""
}

install() {
  # prepare vars
  local name="speedtest-go"
  local bin_name="speedtest"
  # get system os/arch
  local arch="$(os::arch)"
  local kernel="$(os::kernel)"
  # usr_bin_dir
  local usr_bin_dir=$(os::usr_bin_dir)
  local tmp_dir="/tmp/$name"
  # files
  local tmp_file="$name.tar.gz"
  local bin_file="./$name"

  if [ "$arch" = "amd64" ]; then
    arch="x86_64"
  elif [ "$arch" = "arm64" ]; then
    arch="arm64"
  else
    log::error "unknown architecture: $arch"
    exit 1
  fi

  # prepare context
  mkdir -p $tmp_dir
  cd $tmp_dir

  # reference: https://github.com/showwin/speedtest-go/releases
  # example:
  #   https://github.com/showwin/speedtest-go/releases/download/v1.1.5/speedtest-go_1.1.5_Darwin_arm64.tar.gz
  #   https://github.com/showwin/speedtest-go/releases/download/v1.1.5/speedtest-go_1.1.5_Darwin_x86_64.tar.gz
  # generate url
  local url="https://github.com/showwin/speedtest-go/releases/download/$VERSION/${name}_${VERSION#v}_${kernel}_${arch}.tar.gz"
  log::debug "[package][$name][$kernel][$arch] url: $url"

  # download
  os::curl --progress-bar -fSL $url -o $tmp_file

  # extract
  tar -zxvf $tmp_file >>/dev/null 2>&1

  # install
  sudo mv $bin_file $usr_bin_dir/$bin_name

  # clean
  rm -rf $tmp_dir
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  install
  if [ $? -eq 0 ]; then
    log::success "install speedtest success."
    exit 0
  else
    log::error "install speedtest failed."
    exit 1
  fi
}

run() {
  core $@
}

run $@
